{{- if .Values.dnscryptProxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-dnscrypt-proxy-conf
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  dnscrypt-proxy.toml: |
{{ .Values.dnscryptProxy.config | indent 4 }}
{{- end -}}