name: Release Charts

on:
  push:
    branches:
      - master
    paths:
    - 'charts/pihole/**'
    - '!**/README.md'
    - '!**/README.md.gotmpl'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add dependency chart repos
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo add incubator https://charts.helm.sh/incubator 

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_repo_url: https://wolviecb.github.io/pihole-kubernetes/
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
